### ISSUE TITLE
Can't find method com.iwebpp.node.http.http.createServer

### ISSUE THREAD

**Issue by gar1388** [InstantWebP2P/node-android#15]
hi,
 i'm trying to run simply code from the editor:

var http = require('http');
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");
});
server.listen(8000);

but i have error: Can't find method com.iwebpp.node.http.http.createServer
Which is strange because i see the method in the code. I do not know what to do.
The whole log:

D/MainActivity( 1240): start test
D/dalvikvm( 1240): Trying to load lib /data/app-lib/com.iwebpp.nodeandroid-1/libuvpp-jni.so 0xb1d79098
D/dalvikvm( 1240): Added shared lib /data/app-lib/com.iwebpp.nodeandroid-1/libuvpp-jni.so 0xb1d79098
D/dalvikvm( 1240): No JNI_OnLoad found in /data/app-lib/com.iwebpp.nodeandroid-1/libuvpp-jni.so 0xb1d79098, skipping init
D/dalvikvm( 1240): GC_CONCURRENT freed 259K, 9% free 3292K/3612K, paused 4ms+4ms, total 51ms
D/dalvikvm( 1240): GC_CONCURRENT freed 226K, 8% free 3501K/3792K, paused 4ms+4ms, total 44ms
D/dalvikvm( 1240): GC_CONCURRENT freed 242K, 8% free 3719K/4028K, paused 19ms+15ms, total 77ms
D/dalvikvm( 1240): GC_CONCURRENT freed 253K, 7% free 3927K/4208K, paused 4ms+4ms, total 59ms
E/RhinoHost( 1240): org.mozilla.javascript.EvaluatorException: Can't find method com.iwebpp.node.http.http.createServer(function). (UserContent#8)
W/System.err( 1240): java.lang.Exception: Rhino runtime exception: org.mozilla.javascript.EvaluatorException: Can't find method com.iwebpp.node.http.http.createServer(function). (UserContent#8)
W/System.err( 1240):    at com.iwebpp.node.js.rhino.Host.execute(Host.java:312)
W/System.err( 1240):    at com.iwebpp.nodeandroid.MainActivity$2.run(MainActivity.java:202)
W/System.err( 1240):    at java.lang.Thread.run(Thread.java:841)
D/MainActivity( 1240): exit test

**Comment by sequoiar** [comment]
node-android setup nodejs current context alias NCC

please try:

var http = require('http');
var server = http.createServer(NCC, function (request, response) {
response.writeHead(200, {"Content-Type": "text/plain"});
response.end("Hello World\n");
});
server.listen(8000);
