### ISSUE TITLE
Error:Cause: com.android.sdklib.repository.FullRevision, 

### ISSUE THREAD

**Issue by Asscobara** [InstantWebP2P/node-android#17]
Hi, 
I use Android Studio to create apk file from this source.
From some reason, I get Error:Cause: com.android.sdklib.repository.FullRevision,
What is the problem? How to fix it?

Thanks
H.L

**Comment by Asscobara** [comment]
Well, 
I fixed the problem, compiled the apk file, installed on mt android, and the run script does not work at all.....

Please help
H.L

**Comment by sequoiar** [comment]
@Asscobara what's your test step, and please provide error log here.

**Comment by sequoiar** [comment]
no log post
