### ISSUE TITLE
'ARMV7A_FILTER' is missing an input or output annotation

### ISSUE THREAD

**Issue by delltrak** [InstantWebP2P/node-android#24]
Hello 👋🏻 
am try to compile this project using Android Studio Chipmunk | 2021.2.1
and am getting this error below, how can I solve this ? thanks.

Some problems were found with the configuration of task ':app:resolveNativeDependencies' (type 'NativeDependenciesResolverTask').
  - In plugin 'android-native-dependencies' type 'com.nabilhachicha.nativedependencies.task.NativeDependenciesResolverTask' property 'ARMV7A_FILTER' is missing an input or output annotation.

**Comment by sequoiar** [comment]
@delltrak can you try to upgrade node-android to latest android studio.
