### ISSUE TITLE
run JS engine on node-android

### ISSUE THREAD

**Issue by sequoiar** [InstantWebP2P/node-android#4]
some people asked about run overall node.js npm, etc. 

But, Android framework does provide most of device capability. I am still wonder if make sense to run JS engine on JVM.

**Comment by Buggaboo** [comment]
我觉得很有用, 因为我们可以再利用已经编程的javascript code, 可以减少编程时间.

**Comment by sequoiar** [comment]
extend java object from Rhino didn't work due to android disable class file dynamic loading. 

it's great if someone can hack Rhino for android:

https://github.com/InstantWebP2P/rhino-android

**Comment by Buggaboo** [comment]
What do you mean by class file dynamic loading? Have you tried reflection?

**Comment by sequoiar** [comment]
yes, extend java object by reflection and override.

**Comment by Buggaboo** [comment]
I'll have a look, which branch should I look at? Do you already have test-cases?

**Comment by sequoiar** [comment]
https://github.com/InstantWebP2P/rhino-android master branch is ok.

test case: 
check on https://github.com/InstantWebP2P/node-android/blob/master/src/com/iwebpp/node/js/tests/RhinoTest.java 
...
	private boolean testEventEmitter() throws Exception {

**Comment by Buggaboo** [comment]
Have you tried [defining host objects](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Embedding_tutorial)? For example: [Counter.java](http://lxr.mozilla.org/mozilla/source/js/rhino/examples/Counter.java).

```java
/* Use a different package name, not the same as the NDK */
public class EventEmitter2 extends ScriptableObject
{
    /**
     * var server = new EventEmitter2...
     */
    public void jsConstructor(jsObject jsonParams) { mJsonParams = jsonParams; /* then parse with android json*/ }

    public void jsFunction_on(jsString eventName, jsFunction callback) { mEventName = eventName; /*... etc.*/ }

    private String mJsonParams;
    private String mEventName;
    private jsFunction mCallback; // I'm not sure about the type
}
```

Then use it in the rhino context

```java
ScriptableObject.defineClass(scope, EventEmitter2.class);
```

**Comment by sequoiar** [comment]
@Buggaboo didn't try it. and, I mean write js code to extend java native object, not define in java and import to JS context.

**Comment by Buggaboo** [comment]
Sorry I don't follow. Why would you want to do that?

**Comment by sequoiar** [comment]
just for pure JS coder, not mixed java and js.

**Comment by Buggaboo** [comment]
Prototype extension is not possible in rhino?

JavaAdapter should work. Rhino from Oracle contains a crippled version of JavaAdapter. Which one are we using?

**Comment by sequoiar** [comment]
JavaAdapter didn't work with android java runtime. 

for Rhino, I did use https://github.com/mozilla/rhino/releases/tag/Rhino1_7R4_RELEASE

**Comment by Buggaboo** [comment]
I'll work on getting the Rhino CLI to work on android, i.e. add a TextView to MainActivity, so live node.js can be entered. And do some experiments with JavaAdapter or prototype inheritance.

**Comment by sequoiar** [comment]
@Buggaboo really appreciate your work.

**Comment by Buggaboo** [comment]
This can probably fix the `require` issue on Rhino for node.js dependencies: [RequireJS] (http://requirejs.org/).
